project 'GoDefine.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'GoDefine' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!
  # Pods for GoDefine
  pod 'fluid-slider'
  pod 'pop', '~> 1.0'
  pod 'SnapKit'
  pod 'Motion', '~> 3.1.0'
end
